### ISSUE TITLE
loadHorizon and unloadHorizon by record count

### ISSUE THREAD

**Issue by flexyford** [flexyford/impagination#13]
The loadHorizon and unloadHorizon should determine the number of records to load, not the number of pages to load. 

loadHorizon: If some records in a page lie inside the loadHorizon, then load that page.

unloadHorizon: If all the records in a page lie outside the unloadHorizon, then unload that page.

**Comment by cowboyd** [comment]
> unloadHorizon: If the unload Horizon extends into a page, unload the page that follows.

or that preceeds? Perhaps a better statement is "if all the records in a page lie outside the `unloadHorizon`, then unload that page.

**Comment by flexyford** [comment]
Edited description to match your comments

**Comment by flexyford** [comment]
Fixed on #14
