### ISSUE TITLE
Don't emit initial state

### ISSUE THREAD

**Issue by cowboyd** [flexyford/impagination#3]
It turns out that emitting the intial state is prone to causing infinite loops. This is because we're forcing an invocation of the observation logic immediately. Instead, the interface should be

```js
let dataset = new Dataset();
dataset.setReadOffset(10);
```
This decouples the declaration of the dataset from its usage so that it can be defined, but then set into action later.

**Comment by flexyford** [comment]
What about when an initialReadOffset is given?
`var initialReadOffset = options.initialReadOffset;`

**Comment by cowboyd** [comment]
I think we remove initial read offset as a thing. Users have to "kick off" the process by setting the inital read offset.

In other words, we need to separate the "declaration" of the machine from the "start this machine"

**Comment by flexyford** [comment]
thanks!

**Comment by flexyford** [comment]
Fixed on #8 - Pretty straightforward!
