### ISSUE TITLE
`post()` and `put()` methods mutate existing state

### ISSUE THREAD

**Issue by cowboyd** [flexyford/impagination#37]
The `splice()` method changes the contents of the array on which it was called.

https://github.com/flexyford/impagination/blob/7381e66fb8134358da6e90b5109f4575d2a3df21/src/dataset.js#L80-L90

**Comment by flexyford** [comment]
The splice method returns a new state

https://github.com/flexyford/impagination/blob/7381e66fb8134358da6e90b5109f4575d2a3df21/src/state.js#L142-L163

**Comment by cowboyd** [comment]
Oh snap! Totally missed that.
