### ISSUE TITLE
Problem importing Dataset

### ISSUE THREAD

**Issue by mic7010** [flexyford/impagination#38]
When importing the Dataset I am getting an error 

'Unable to resolve module 'util' from node-modules/binary-search-tree/lib/avltree.js'

I am running 0.44.1 of React Native

**Comment by ricwa230** [comment]
I had the same problem and it is because the node-util module does not exist in RN. A quick fix that worked for me was simply `npm install util` or `yarn add util`. Hope this info helps you.

**Comment by cowboyd** [comment]
Looks like this is a duplicate of #40
