### ISSUE TITLE
Implement Lazy interface

### ISSUE THREAD

**Issue by cowboyd** [flexyford/impagination#4]
Instead of: 

```javascript
for (var i = 0; i < state.records.length; i++) {
  console.log(state.records[i]);
}
```
we let you look up the record directly off of the state:

```javascript
for (var i = 0; i < state.length; i++) {
  console.log(state.get(i));
}
```

That way we can be lazy about materializing the record array instead of doing it every time. `state.records` then goes away

**Comment by flexyford** [comment]
How do we handle getting the length of records ie
`state.records.length`

We have `state.totalSize` which has never been implemented

**Comment by cowboyd** [comment]
put the `length` property right on state. This is the only eager calculation.

**Comment by cowboyd** [comment]
`state.records` will cease to exist.

**Comment by cowboyd** [comment]
Ticket description was updated to reflect using `state.length` instead of `state.records.length`

**Comment by flexyford** [comment]
@cowboyd can i get a review on #10 please
