### ISSUE TITLE
binary-search-tree uses node.js util module

### ISSUE THREAD

**Issue by deive** [flexyford/impagination#40]
Hi, your dependency binary-search-tree uses the node.js util module, so this is not working in react-native. See https://github.com/louischatriot/node-binary-search-tree/issues/14
To get around this you can:
1. npm install util --save
2. Use my pull that just copies the single required method to binary-search-tree, so it doesn't require util - https://github.com/louischatriot/node-binary-search-tree/pull/17

**Comment by flexyford** [comment]
Thanks for your help. fixed in #44
