### ISSUE TITLE
Filter is not applied after Dataset reset is called

### ISSUE THREAD

**Issue by tiberiumihai** [flexyford/impagination#41]
I'm using this with a RefreshControl in React-Native.

When I'm pulling-to-refresh, I'm calling Dataset.reset, which should reset the state, but the filters that I have added are no longer take in consideration because filter callback is not passed into state in Dataset.reset function.

**Comment by tiberiumihai** [comment]
#42 Added a PR for this.

**Comment by flexyford** [comment]
Thanks for the help! Fixed in #42
