### ISSUE TITLE
problems with react native 0.50.3 and react 16.0.0 in module binary-search-tree

### ISSUE THREAD

**Issue by rolignu2** [flexyford/impagination#46]
when importing Dataset as the example says, it gives a module error, checking the code a bit and the problem causes it

import {AVLTree} from 'binary-search-tree';
import {BinarySearchTree} from 'binary-search-tree';

the error is inside page-tree.js

any alternative for that library to react native?

"dependencies": {
		"binary-search-tree": "^0.2.6",
		"connect": "^3.6.5",
		"impagination": "^1.0.0-alpha.3",
		"link": "^0.1.5",
		"native-base": "^2.3.3",
		"react": "^16.0.0",
		"react-native": "^0.50.3",
		"react-native-animatable": "^1.2.4",
		"react-native-code-push": "^5.0.0-beta",
		"react-native-fbsdk": "^0.6.3",
		"react-native-fetch-polyfill": "^1.1.2",
		"react-native-restart": "0.0.4",
		"react-native-router-flux": "^4.0.0-beta.21",
		"react-native-vector-icons": "^4.4.2",
		"realm": "^1.13.0",
		"underscore": "^1.8.3"
	},

**Comment by cowboyd** [comment]
Can you post the _exact_ error you're getting?

**Comment by rolignu2** [comment]
<img width="1280" alt="captura" src="https://user-images.githubusercontent.com/2179292/32813129-34919b5a-c96e-11e7-92d2-9fac37994e46.png">

**Comment by rolignu2** [comment]
solved: I could install the useful library and with that it could be fixed
