### ISSUE TITLE
Update load and unload object to fix off-by-one error

### ISSUE THREAD

**Issue by cowboyd** [flexyford/impagination#5]
Looking at the color demo, you can see that pages are only loaded once they are "fully" contained within the load horizon. Instead, we should load the page the moment the end of the load horizon "breaches" the first record of the page.

**Comment by flexyford** [comment]
I'm planning to implement the following. Let me know if this table makes much sense. Should consider adding a more clear version of this table in the README?

action | inc readOffset | dec readOffset
---------- | ------------------ | --------------------
load | when "breaching" first record of unrequested page | when "breaching" last record of unrequested page
unload | when "passing" last record of resolved page | when "passing" first record of resolved page

**Comment by flexyford** [comment]
Fixed on #9
