### ISSUE TITLE
Rehabilitate the test suite

### ISSUE THREAD

**Issue by cowboyd** [flexyford/impagination#7]
Convert the remaining test cases to use the simulation server

**Comment by flexyford** [comment]
* Defining Dataset
* setReadOffset to the beginning
  * resolve promises
  * reject promises
* setReadOffset to the middle (loadHorizon: 1 / unloadHorizon: 2)
  * inc readOffset
  * dec readOffset
* setReadOffset to the end
  * inc readOffset
